from app.models.base import Base
from app.models.event import EventModel
from app.models.college import CollegeModel
from app.models.admin import AdminModel
from app.models.scanner import ScannerModel
from app.models.setting import SettingModel
from app.models.graduate import GraduateModel
from app.models.university_record import UniversityRecordModel
from app.models.ticket import TicketModel
from app.models.payment import PaymentModel
from app.models.qr_code import QrCodeModel
from app.models.otp_code import OtpCodeModel
from app.models.audit_log import AuditLogModel
